# -*- encoding: utf-8 -*-
from django.contrib import admin
from app.models import *
admin.site.register(Cargo)
admin.site.register(CargoOT)
admin.site.register(Comuna)
admin.site.register(Cliente)
admin.site.register(Marca)
admin.site.register(Modelo)
admin.site.register(FormaPago)
admin.site.register(Empleado)
admin.site.register(Venta)
admin.site.register(EstadoOT)
admin.site.register(Vehiculo)
admin.site.register(OrdenDeTrabajo)
admin.site.register(Servicio)
admin.site.register(Proveedor)
admin.site.register(TipoMaterial)
admin.site.register(Material)
admin.site.register(DetalleOT)
admin.site.register(DetalleVenta)
admin.site.register(EmpleadoOT)
admin.site.register(Herramienta)
admin.site.register(LogSistema)
admin.site.register(Propiedad)
admin.site.register(TMProp)
admin.site.register(MaterialProp)
admin.site.register(ServicioHerramienta)
admin.site.register(ServicioMaterial)